---
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: change for list/summaries - limit to 30 words for best fit
- name: date
  label: Date
  type: text
  hidden: false
  default: ''
- name: productName
  label: Productname
  type: text
  hidden: false
  default: ''
- name: logo
  label: Logo
  type: text
  hidden: false
  default: "/img/logo.jpg"
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default:
  - ''
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default:
  - ''
- name: downloadUrl
  label: Downloadurl
  type: text
  hidden: false
  default: ''
- name: website
  label: Website
  type: text
  hidden: false
  default: ''
